### ISSUE TITLE
RESOURCE_EXHAUSTED; VK_ERROR_OUT_OF_DEVICE_MEMORY; 

### ISSUE THREAD

**Issue by Areshkew** [nod-ai/SHARK#1223]
vmaCreateBuffer; while invoking native function hal.device.queue.alloca; while calling import;

Graphics Card: Rx 580 - 8GB

**Comment by Areshkew** [comment]
Getting this issue when generating images.

**Comment by nirvedhmeshram** [comment]
@Areshkew can you retry with the latest release, we have made changes that might have solved this issue

**Comment by Areshkew** [comment]
> @Areshkew can you retry with the latest release, we have made changes that might have solved this issue

I can't run models in this version. I'm getting this error now:

Traceback (most recent call last):
  File "gradio\routes.py", line 401, in run_predict
  File "gradio\blocks.py", line 1302, in process_api
  File "gradio\blocks.py", line 1039, in call_function
  File "anyio\to_thread.py", line 31, in run_sync
  File "anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
  File "anyio\_backends\_asyncio.py", line 867, in run
  File "gradio\utils.py", line 491, in async_iteration
  File "ui\txt2img_ui.py", line 146, in txt2img_inf
  File "apps\stable_diffusion\src\pipelines\pipeline_shark_stable_diffusion_utils.py", line 308, in from_pretrained
  File "apps\stable_diffusion\src\models\model_wrappers.py", line 143, in __init__
  File "apps\stable_diffusion\src\utils\utils.py", line 496, in preprocessCKPT
  File "diffusers\pipelines\stable_diffusion\convert_from_ckpt.py", line 1158, in download_from_original_stable_diffusion_ckpt
  File "diffusers\configuration_utils.py", line 596, in inner_init
  File "diffusers\models\unet_2d_condition.py", line 354, in __init__
  File "diffusers\models\unet_2d_blocks.py", line 248, in get_up_block
  File "diffusers\models\unet_2d_blocks.py", line 1743, in __init__
  File "diffusers\configuration_utils.py", line 596, in inner_init
  File "diffusers\models\transformer_2d.py", line 179, in __init__
  File "diffusers\models\transformer_2d.py", line 180, in <listcomp>
  File "diffusers\models\attention.py", line 228, in __init__
  File "diffusers\models\attention_processor.py", line 92, in __init__
  File "torch\nn\modules\linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 6553600 bytes.

I even activate "Low Vram" Option and it didn't work.

**Comment by monorimet** [comment]
Looks like CPU not GPU but I may be wrong

**Comment by Areshkew** [comment]
> Looks like CPU not GPU but I may be wrong

"RX 580X series vulkan 0" is selected. 
What could be happening?

**Comment by Areshkew** [comment]
I just fixed my last new error, and I verified this error is fixed.

Thank you for your time and attention :D
