### ISSUE TITLE
SD: Txt2img errors loading .vmfb when ROCM device selected for generation

### ISSUE THREAD

**Issue by one-lithe-rune** [nod-ai/SHARK#1801]
Trying to generate with txt2img (SD 2.1 base) from Shark studio, selecting a rocm device (7900 xtx) gives me the following:

```
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
shark_tank local cache is located at C:\Users\skapusniak\.local/shark_tank/ . You may change this by setting the --local_tank_cache= flag
gradio temporary image cache located at C:\develop\SHARK\shark_tmp/gradio. You may change this by setting the GRADIO_TEMP_DIR environment variable.
No temporary images files to clear.
vulkan devices are available.
metal devices are not available.
cuda devices are not available.
rocm devices are available.
local-sync devices are available.
local-task devices are available.
Running on local URL:  http://0.0.0.0:8080

To create a public link, set `share=True` in `launch()`.
Tuned models are currently not supported for this setting.
Checking for updates from gs://shark_tank/nightly
Model artifacts for euler_scale_model_input_fp16 found at C:\Users\skapusniak\.local/shark_tank/...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 640/640 [00:00<00:00, 24.6kB/s]
Local and upstream hashes match. Using cached model artifacts.
Verifying that model artifacts were downloaded successfully to C:\Users\skapusniak\.local/shark_tank/euler_scale_model_input_fp16_torch\euler_scale_model_input_fp16_torch.mlir...
No vmfb found. Compiling and saving to C:\develop\SHARK\euler_scale_model_input_fp16.vmfb
Configuring for device:rocm://0
Specific device selection only supported for vulkan now.Proceeding with rocm://0 as device.
Found a ROCm installation at C:\Program Files\AMD\ROCm\5.5\.
Found rocm arch gfx1100...
Saved vmfb in C:\develop\SHARK\euler_scale_model_input_fp16.vmfb.
Loading module C:\develop\SHARK\euler_scale_model_input_fp16.vmfb...
failed to download model, falling back and using import_mlir
No vmfb found. Compiling and saving to C:\develop\SHARK\euler_scale_model_input_1_512_512_rocm_fp16.vmfb
Configuring for device:rocm://0
Specific device selection only supported for vulkan now.Proceeding with rocm://0 as device.
Saved vmfb in C:\develop\SHARK\euler_scale_model_input_1_512_512_rocm_fp16.vmfb.
Loading module C:\develop\SHARK\euler_scale_model_input_1_512_512_rocm_fp16.vmfb...
forward_dispatch_0: error: unable to find ld.lld in PATH
forward_dispatch_0: error: unable to find ld.lld in PATH
Traceback (most recent call last):
  File "C:\develop\SHARK\apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 115, in compile
    self.scaling_model = get_shark_model(
                         ^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\utils.py", line 110, in get_shark_model
    return _compile_module(shark_module, model_name, extra_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\utils.py", line 83, in _compile_module
    shark_module.load_module(path, extra_args=extra_args)
  File "C:\develop\SHARK\shark\shark_inference.py", line 215, in load_module
    params = load_flatbuffer(
             ^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\iree_utils\compile_utils.py", line 463, in load_flatbuffer
    vmfb, config, temp_file_to_unlink = load_vmfb_using_mmap(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\iree_utils\compile_utils.py", line 406, in load_vmfb_using_mmap
    ctx.add_vm_module(mmaped_vmfb)
  File "C:\develop\shark\shark.venv\Lib\site-packages\iree\runtime\system_api.py", line 271, in add_vm_module
    self.add_vm_modules((vm_module,))
  File "C:\develop\shark\shark.venv\Lib\site-packages\iree\runtime\system_api.py", line 268, in add_vm_modules
    self._vm_context.register_modules(vm_modules)
RuntimeError: Error registering modules: C:\actions-runner\w\SRT\SRT\c\experimental\rocm\status_util.c:31: INTERNAL; rocm driver error 'hipErrorInvalidKernelFile' (218): invalid kernel file; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:250 -

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\blocks.py", line 1121, in call_function
    prediction = await utils.async_iteration(iterator)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\utils.py", line 350, in async_iteration
    return await iterator.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\utils.py", line 343, in __anext__
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2101, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 828, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\utils.py", line 326, in run_sync_iterator_async
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "C:\develop\shark\shark.venv\Lib\site-packages\gradio\utils.py", line 695, in gen_wrapper
    yield from f(*args, **kwargs)
  File "C:\develop\SHARK\apps\stable_diffusion\web\ui\txt2img_ui.py", line 160, in txt2img_inf
    global_obj.set_schedulers(get_schedulers(model_id))
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\schedulers\sd_schedulers.py", line 103, in get_schedulers
    schedulers["SharkEulerDiscrete"].compile()
  File "C:\develop\SHARK\apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 130, in compile
    _import(self)
  File "C:\develop\SHARK\apps\stable_diffusion\src\schedulers\shark_eulerdiscrete.py", line 93, in _import
    self.scaling_model, _ = compile_through_fx(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\utils.py", line 178, in compile_through_fx
    _compile_module(shark_module, extended_model_name, extra_args),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\apps\stable_diffusion\src\utils\utils.py", line 83, in _compile_module
    shark_module.load_module(path, extra_args=extra_args)
  File "C:\develop\SHARK\shark\shark_inference.py", line 215, in load_module
    params = load_flatbuffer(
             ^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\iree_utils\compile_utils.py", line 463, in load_flatbuffer
    vmfb, config, temp_file_to_unlink = load_vmfb_using_mmap(
                                        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\develop\SHARK\shark\iree_utils\compile_utils.py", line 406, in load_vmfb_using_mmap
    ctx.add_vm_module(mmaped_vmfb)
  File "C:\develop\shark\shark.venv\Lib\site-packages\iree\runtime\system_api.py", line 271, in add_vm_module
    self.add_vm_modules((vm_module,))
  File "C:\develop\shark\shark.venv\Lib\site-packages\iree\runtime\system_api.py", line 268, in add_vm_modules
    self._vm_context.register_modules(vm_modules)
RuntimeError: Error registering modules: C:\actions-runner\w\SRT\SRT\c\experimental\rocm\status_util.c:31: INTERNAL; rocm driver error 'hipErrorInvalidKernelFile' (218): invalid kernel file; while invoking native function hal.executable.create; while calling import;
[ 1]   native hal.executable.create:0 -
[ 0] bytecode module@1:250 -
```

**Comment by monorimet** [comment]
Hey, please try after deleting the .vmfb -- if you still have problems let me know, I saw this a few times during testing

**Comment by monorimet** [comment]
For ld.lld I got it working with `New-Item -ItemType SymbolicLink -Path "C:\<path-to>\ROCm\5.5\bin\ld.lld" -Target "C:\<path-to>\ROCm\5.5\bin\ld.lld.exe"` and `$env:Path += ';C:\AMD\ROCm\5.5\bin'`

You might want to use both of these along with freshly generated .vmfbs.

This is just coming out of experimental stage so thank you for bearing with us on the QOL side.

**Comment by njsharpe** [comment]
Update: I tried this out and the ld.lld fix works as intended, however once it attempted to load the unet512 for a 512x768 generation, I got this output and it almost crashed my GPU.

```
<regular output until here>

Configuring for device:rocm://0
Specific device selection only supported for vulkan now.Proceeding with rocm://0 as device.
Saved vmfb in D:\Stable\stable-diffusion-shark\apps\stable_diffusion\web\unet512_1_64_512_768_fp16_divineelegancemix_V6_rocm.vmfb.
Loading module D:\Stable\stable-diffusion-shark\apps\stable_diffusion\web\unet512_1_64_512_768_fp16_divineelegancemix_V6_rocm.vmfb...
0it [00:00, ?it/s]::: Detailed report (took longer than 5.0s):
  +1.008749008178711ms: Load to device: (1, 4, 64, 96)
  +16.040325164794922ms: Load to device: (1,)
  +16.040325164794922ms: Load to device: (2, 512, 768)
  +16.040325164794922ms: Load to device: torch.Size([])
  +17.618417739868164ms: Invoke function: forward
  +69836.29822731018ms: Invoke complete
1it [01:09, 69.87s/it]::: Detailed report (took longer than 5.0s):
  +1.0058879852294922ms: Load to device: (1, 4, 64, 96)
  +1.0058879852294922ms: Load to device: (1,)
  +1.0058879852294922ms: Load to device: (2, 512, 768)
  +1.0058879852294922ms: Load to device: torch.Size([])
  +1.0058879852294922ms: Invoke function: forward
Press any key to continue . . .
```

69836ms = ~70s of my GPU being frozen. It did crash Adrenaline and prompted a crash report. Other info:
- Win11 22H2 (22621.2215)
- 7900 XTX (Adrenaline 23.8.1)
- HIP 5.5 (0-3e8db564)

**Comment by njsharpe** [comment]
@powderluv No WHL was generated for [Candidate 247](https://github.com/nod-ai/SRT/releases/tag/candidate-20230829.247). I will attempt a build directly with the `setup.py` files provided for the runtime and compiler, but it would be my first time trying. Will update if successful.

**Comment by powderluv** [comment]
ah the builder was down. I have started it again so we should get a build soon

**Comment by njsharpe** [comment]
> ah the builder was down. I have started it again so we should get a build soon

Cheers, because I cannot build this for windows for the life of me. I can build for linux, but I can't test on linux because it's fake linux (WSL). Ignoring that, I'll try this out in an hour to two.

**Comment by njsharpe** [comment]
> ah the builder was down. I have started it again so we should get a build soon

Testing completed, successfully ran with a ROCm device for 512x. Compile times were about the same on my device, ~300s before an image was generated for first run. However, performance is _very_ poor. At 30 steps, one image took 18s @ 1.65it/s. I noticed the following:

- It seems my GPU was not actually used for image generation, but my CPU also wasn't used? Both sat at 1% and 5% usage the entire time during image generation.
- It seems ROCm uses less RAM overall on first generation, and was more consistent in its allocation, ranging between 10GB and 15GB for the entire time, whereas Vulkan would range between 15GB and 24GB.
- Image generation was fine and I noticed no decrease in quality of the result.

\* Note that this was a custom checkpoint (SD 1.5) and VAE, if that's of any importance.

**Comment by powderluv** [comment]
Thank you for testing. Our current focus with ROCM is to remove the need for the HIP SDK (so you can run on any stock Windows system). We have WMMA pipeline being enabled and we are seeing big speed up with it. Once all of that is enabled we will tune the models further.

**Comment by one-lithe-rune** [comment]
Sorry didn't get time to try again until now. 

I had similar results to @njsharpe, including the driver timeout per iteration before prior to updating the venv. However I *didn't* get the low GPU utilization, it shows 100% for me.

Adding the `ldd` symlink, clearing out some .vmfbs and some things from local shark tank, and doing `.\setup_venv.ps1 --force` pretty much clears all the crashing issues so far.

FWIW (rdna3, 7900 XTX, windows 10):

- 1.81 it/s for with SD 2.1 base and SharkEuler @ 512x512
- 1.67 it/s for with a 1.5 based model (Cyberrealistic 3.1) @ 512x512

**Comment by powderluv** [comment]
Thank you for testing. Next few days we should be landing more of the ROCM changes and this number can only go up 😀
